name: Creates a branch for issue on issue creation

# Controls when the workflow will run
on:
  # Triggers the workflow on issues events but only when issue is opened
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create_branch"
  create_branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: "origin/milestone-membership-nfts"

      # Runs a single command using the runners shell
      - name: Runs branch creation script
        run: |
          echo $(git branch)
          echo $(${{ github.event.issues.issue }})

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
